
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	    <TargetFramework>netstandard2.0</TargetFramework>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<RootNamespace>Contensive.PageWidgetExample</RootNamespace>
		<DelaySign>false</DelaySign>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
		<OptionStrict>On</OptionStrict>
		<AssemblyName>PageWidget</AssemblyName>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
		<LangVersion>latest</LangVersion>
		<SignAssembly>True</SignAssembly>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Views\**" />
		<EmbeddedResource Remove="Views\**" />
		<None Remove="Views\**" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Microsoft.VisualBasic" />
		<PackageReference Include="Contensive.CPBaseClass" Version="26.3.17.1" />
		<PackageReference Include="Contensive.DbModels" Version="26.3.17.1" />
		<PackageReference Include="Contensive.DesignBlockBase" Version="25.4.26.1" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.5" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System" />
		<Reference Include="System.Data" />
		<Reference Include="System.Xml" />
		<Reference Include="System.Core" />
		<Reference Include="System.Xml.Linq" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="System.Net.Http" />
	</ItemGroup>
</Project>